SELECT * FROM T_EMP;


SELECT ENAME , sal
FROM T_EMP 
WHERE sal > (SELECT sal FROM T_EMP WHERE ENAME = 'SCOTT');

SELECT name,HEIGHT 
from T_STUDENT 
WHERE HEIGHT = (SELECT max(HEIGHT) FROM T_STUDENT);

SELECT s.NAME , d.DNAME 
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO AND s.DEPTNO1 = (SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나'); 

SELECT p.NAME , p.HIREDATE , d.DNAME 
FROM T_PROFESSOR  p, T_DEPARTMENT d
WHERE p.HIREDATE > (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권')
		AND p.DEPTNO = d.DEPTNO;

SELECT *
FROM T_emp2 ;


SELECT name, WEIGHT 
FROM T_STUDENT 
WHERE DEPTNO1 = 101 AND WEIGHT > (SELECT AVG(WEIGHT) FROM T_STUDENT WHERE DEPTNO1 = 101);

SELECT NAME , HIREDATE , PAY 
FROM T_PROFESSOR 
WHERE HIREDATE = (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '심슨') AND 
		PAY < (SELECT PAY FROM T_PROFESSOR WHERE name = '조인형');
		
SELECT name , post , TO_CHAR(pay,'999,999,999') || '원'
FROM t_emp2
WHERE pay >ANY (SELECT pay FROM T_EMP2 WHERE POST = '과장')

SELECT NAME , GRADE , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT <ALL (SELECT MIN(WEIGHT ) FROM T_STUDENT WHERE GRADE = 4)

