SELECT GRADE  ,  max(HEIGHT)
FROM T_STUDENT 
GROUP BY GRADE;

SELECT GRADE , NAME , HEIGHT 
FROM T_STUDENT
WHERE (GRADE, HEIGHT) IN 
(SELECT GRADE  ,  max(HEIGHT)
FROM T_STUDENT 
GROUP BY GRADE
)
ORDER BY NAME ASC;

SELECT p.PROFNO , p.NAME , p.HIREDATE , d.DNAME 
FROM T_PROFESSOR p , T_DEPARTMENT d
WHERE (p.DEPTNO , p.HIREDATE) IN (SELECT DEPTNO , min(HIREDATE) FROM T_PROFESSOR GROUP BY DEPTNO ) AND p.DEPTNO = d.DEPTNO 
ORDER BY d.DNAME ASC;

SELECT * from T_PROFESSOR ;

SELECT PROFNO , min(HIREDATE) FROM T_PROFESSOR GROUP BY PROFNO;

SELECT  NAME , POST , PAY 
FROM T_EMP2
WHERE (POST , PAY ) IN (SELECT POST , max(PAY) FROM t_emp2 GROUP BY POST ) 
ORDER BY pay ASC;

SELECT * FROM T_DEPT2; 

SELECT * from t_emp2;

SELECT d.DNAME , e.NAME , e.PAY * 12 
FROM T_EMP2 e, T_DEPT2 d
WHERE e.DEPTNO = d.DCODE AND e.PAY <ALL (SELECT avg(PAY) FROM t_emp2 GROUP BY DEPTNO);


SELECT a.NAME , a.POST 
FROM T_EMP2 a
WHERE a.pay >= (SELECT avg(b.pay) FROM t_emp2 b WHERE a.POST = b.POST)
;

SELECT avg(b.pay) FROM t_emp2 b WHERE '과장' = b.POST;

