SELECT 1+1 FROM dual;
SELECT '1' + 1 FROM dual;

SELECT TO_NUMBER('1') + 1 FROM dual;
	
-- TO_CHAR 함수  날짜 -> 문자
SELECT 
	SYSDATE,
	TO_CHAR(SYSDATE,'YYYY'),
	TO_CHAR(SYSDATE,'yy' ) ,
	TO_CHAR(SYSDATE,'YEAR')
	FROM dual;
	
SELECT 
	TO_CHAR(sysdate, 'DD'),
	TO_CHAR(SYSDATE, 'DDth') 
FROM dual;

SELECT 
TO_CHAR(sysdate, 'MM'),
TO_CHAR(SYSDATE, 'MON') 월3자리,  -- 7월
	TO_CHAR(SYSDATE, 'MONTH')  월전체,  -- 7월
	TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE=ENGLISH') 월영문3자리,  -- JUL
	TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(대)", -- JULY
	TO_CHAR(SYSDATE, 'month', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(소)",  -- july
	TO_CHAR(SYSDATE, 'Month', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(첫글자대)" -- July
	FROM dual;


SELECT 
	TO_CHAR(SYSDATE, 'HH24') 시24hr,
	TO_CHAR(SYSDATE, 'HH')  시12hr,
	TO_CHAR(SYSDATE, 'MI') 분,
	TO_CHAR(SYSDATE, 'SS') 초,
	TO_CHAR(SYSDATe, 'HH:Mi:SS' ) 
FROM dual;

SELECT 
SYSDATE, TO_CHAR(SYSDATE, 'YYYY:MM:DD HH24:MI:SS' ) 
FROM dual;

SELECT 
SYSDATE, TO_CHAR(SYSDATE, 'YYYY"년"MM"월"DD"일" HH24"시"MI"분"SS"초"' ) 
FROM dual;

--4302
SELECT NAME ,BIRTHDAY 
FROM T_STUDENT 
WHERE TO_CHAR(BIRTHDAY, 'MM') = 03


-- TO_CHAR : 대소문자 지정예
SELECT
SYSDATE,
TO_CHAR(SYSDATE, 'Dy Month DD, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A1,
TO_CHAR(SYSDATE, 'dy month dd, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A2,
TO_CHAR(SYSDATE, 'DY MONTH DD, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A3
FROM DUAL;


SELECT 
1234 , TO_CHAR(1234,'99999') "9하나당 한자리",
	TO_char(1234, '09999'),
	TO_char(1234, '$9999'),
	TO_char(1234.1234, '9999.99')
FROM dual;

SELECT NAME , TO_CHAR(PAY * 12 + NVL(BONUS,0), '9,999') 연봉 
FROM T_PROFESSOR 
WHERE DEPTNO = 101;

SELECT TO_NUMBER('12.423')
FROM dual;

SELECT 
TO_DATE('2020-04-05','YYYY-MM-DD')TO_DATE 
FROM dual;

SELECT NAME 이름, HIREDATE 입사일, pay * 12 연봉, (pay * 12)*1.1 "인상된 연봉"
FROM T_PROFESSOR 
WHERE TO_CHAR(HIREDATE, 'YYYY') < 2000 

SELECT *
FROM T_PROFESSOR;