-- INITCAP 함수

-- #4101
SELECT INITCAP('pretty girl') 
FROM DUAL;

-- #4102
SELECT INITCAP(ID)
FROM T_STUDENT
WHERE DEPTNO1 = 201;

-- LOWER(), UPPER()

-- #4103
SELECT NAME ,ID ,lower(id) 소문자 ,upper(ID) 대문자
FROM T_STUDENT 
WHERE DEPTNO1 = 201;

--length() / lengthb()

-- #4104
SELECT NAME 이름 , ID , LENGTH (ID) 글자수
FROM T_STUDENT 
WHERE LENGTH(ID) >= 9

-- #4105
SELECT NAME 이름, LENGTH(NAME) 길이, LENGTHB(NAME) 바이트 
FROM T_STUDENT 
WHERE DEPTNO1 = 201;

--concat(문자열1,문자열2)

--#4106
SELECT CONCAT(NAME,"POSITION") 
FROM T_PROFESSOR 
WHERE DEPTNO = 101;

--subSTR(문자열 , 시작위치, 추출할 글자수)

--#4107
SELECT SUBSTR(JUMIN, 1, 6)  
FROM T_STUDENT 
WHERE DEPTNO1 = 101;

-- #4108
SELECT NAME ,SUBSTR(JUMIN, 1, 6)
FROM T_STUDENT 
WHERE SUBSTR(JUMIN, 4,1) = 8 ;

--#4109
SELECT NAME , JUMIN 
FROM T_STUDENT 
WHERE SUBSTR(JUMIN , 7, 1) = 2 AND GRADE  = 4;

--instr(문자열, 찾는 문자열, 시작위치, 몇번째 등장)

--#4110
SELECT NAME , TEL , INSTR(TEL, ')', 1, 1) 
FROM T_STUDENT 
WHERE DEPTNO1 = 101;

--#4111
SELECT NAME , TEL , SUBSTR(TEL , 1 , instr(TEL , ')' , 1 , 1)-1) 
FROM T_STUDENT 
WHERE DEPTNO1 = 101;

--lpad(문자열 , 자릿수, 채움문자)

--#4112
SELECT id , LPAD(id, 10 , '$') 
FROM T_STUDENT 
WHERE DEPTNO1 = 101;

--4113
SELECT LPAD(DNAME,10,1234)
FROM T_DEPT2;

--4114
SELECT RPAD(id , 12 , '*') 
FROM T_STUDENT;

--4118
SELECT name, REPLACE(name, SUBSTR(name,1,1), '#') 학생

FROM T_STUDENT
WHERE DEPTNO1 = 102;

--4119
SELECT name, REPLACE(name, SUBSTR(name,2,1), '#') 학생
FROM T_STUDENT 
WHERE DEPTNO1 = 101;

--4120
SELECT NAME , REPLACE(JUMIN, SUBSTR(JUMIN, 7, 7), '*******' )
FROM T_STUDENT 
WHERE DEPTNO1 =101;

--4121
SELECT NAME , TEL , REPLACE(TEL, SUBSTR(tel, INSTR(tel,')')+1,3), '###') 전화번호
FROM T_STUDENT 
WHERE DEPTNO1  =102;
